### ISSUE TITLE
Clarifications about the Bower requirement?

### ISSUE THREAD

**Issue by alphang** [acrolinx/acrolinx-scale#7]
`report.html` requires `<script src="./bower_components/d3/d3.js"></script>`

Can you clarify in the docs on how we are supposed to retrieve these bower components?
(Also, it seems that newer projects don't recommend Bower anymore.)

**Comment by acrork** [comment]
Please see: https://github.com/acrolinx/acrolinx-scale#how-set-up-scale to get scale running.

Acrolinx supports a new way of presenting the data, called Content-Analyse-Dashboard.

To discuss your use case, please contact the Acrolinx Support.
